import { useState, useEffect, useMemo, useRef } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import {
  VscArrowLeft,
  VscEye,
  VscCode,
  VscFileCode,
  VscListTree,
  VscLayout,
  VscZoomIn,
  VscZoomOut,
  VscSettings,
  VscChecklist,
  VscCircleFilled,
  VscSearch,
  VscClose,
  VscSave,
  VscMarkdown,
  VscJson,
  VscCopy,
  VscCheck,
} from 'react-icons/vsc';

export default function DocBuilder() {
  const { repoId } = useParams();
  const navigate = useNavigate();
  const printRef = useRef(null);

  const [files, setFiles] = useState([]);
  const [contents, setContents] = useState({});
  const [selectedIds, setSelectedIds] = useState([]);
  const [allSelected, setAllSelected] = useState(false);
  const [showSidebar, setShowSidebar] = useState(true);
  const [viewMode, setViewMode] = useState('preview'); // 'preview' | 'source' | 'split'
  const [fontSize, setFontSize] = useState(14);
  const [showLineNumbers, setShowLineNumbers] = useState(true);
  const [showFilePaths, setShowFilePaths] = useState(true);
  const [includeTOC, setIncludeTOC] = useState(true);
  const [loading, setLoading] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [copied, setCopied] = useState(false);
  const [exportFormat, setExportFormat] = useState('markdown'); // 'markdown' | 'html'
  const [showExportMenu, setShowExportMenu] = useState(false);

  useEffect(() => {
    loadFiles();
  }, [repoId]);

  const loadFiles = async () => {
    setLoading(true);
    const list = await window.api.getFilesForRepo(Number(repoId));
    setFiles(list || []);

    // Pre-load contents for files that already have AI docs
    const contentsMap = {};
    for (const file of list) {
      if (file.header || file.explanation) {
        const full = await window.api.getFileContent(file.id);
        contentsMap[file.id] = full;
      }
    }
    setContents(contentsMap);
    setLoading(false);
  };

  const handleToggle = async (id) => {
    setSelectedIds((prev) => {
      const newSelection = prev.includes(id) ? prev.filter((i) => i !== id) : [...prev, id];
      setAllSelected(newSelection.length === files.length);
      return newSelection;
    });

    // Load content if not already loaded
    if (!contents[id]) {
      const full = await window.api.getFileContent(id);
      setContents((prev) => ({ ...prev, [id]: full }));
    }
  };

  const handleSelectAll = async () => {
    if (allSelected) {
      setSelectedIds([]);
      setAllSelected(false);
    } else {
      const allIds = files.map((f) => f.id);
      setSelectedIds(allIds);
      setAllSelected(true);

      // Load all contents
      const contentsMap = { ...contents };
      for (const file of files) {
        if (!contentsMap[file.id]) {
          const full = await window.api.getFileContent(file.id);
          contentsMap[file.id] = full;
        }
      }
      setContents(contentsMap);
    }
  };

  const selectedFiles = useMemo(() => {
    return files.filter((f) => selectedIds.includes(f.id)).map((f) => contents[f.id] || f);
  }, [files, selectedIds, contents]);

  // Filter files by search
  const filteredFiles = useMemo(() => {
    if (!searchQuery.trim()) return files;
    const query = searchQuery.toLowerCase();
    return files.filter(
      (f) =>
        f.filename.toLowerCase().includes(query) ||
        f.filepath.toLowerCase().includes(query) ||
        (f.header && f.header.toLowerCase().includes(query)),
    );
  }, [files, searchQuery]);

  // Generate Markdown
  const generateMarkdown = useMemo(() => {
    let md = '';

    // Title
    md += `# Repository Documentation\n\n`;
    md += `*Generated on ${new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
      hour: '2-digit',
      minute: '2-digit',
    })}*\n\n`;
    md += `---\n\n`;

    // Table of Contents
    if (includeTOC && selectedFiles.length > 0) {
      md += `## 📑 Table of Contents\n\n`;
      selectedFiles.forEach((file, index) => {
        const title = file.header || file.filename;
        md += `${index + 1}. [${title}](#section-${index + 1})\n\n`;
      });
      md += `---\n\n`;
    }

    // File sections
    selectedFiles.forEach((file, index) => {
      const title = file.header || file.filename;

      md += `<a id="section-${index + 1}"></a>\n\n`;
      md += `## ${index + 1}. ${title}\n\n`;

      if (showFilePaths && file.filepath) {
        md += `**File:** \`${file.filepath}\`\n\n`;
      }

      if (file.explanation) {
        md += `### 📝 Overview\n\n${file.explanation}\n\n`;
      }

      if (file.code) {
        const lang = file.filetype || '';
        md += `### 💻 Source Code\n\n\`\`\`${lang}\n${file.code}\n\`\`\`\n\n`;
      }

      if (file.footnote) {
        md += `### 📌 Notes\n\n${file.footnote}\n\n`;
      }

      md += `---\n\n`;
    });

    // Footer
    md += `\n---\n\n`;
    md += `*Documentation generated by RepoDocs*\n`;

    return md;
  }, [selectedFiles, includeTOC, showFilePaths]);

  // Generate HTML
  const generateHTML = useMemo(() => {
    return `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Repository Documentation</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            line-height: 1.6;
            color: #333;
            background: #fff;
            padding: 2rem;
            max-width: 1000px;
            margin: 0 auto;
        }
        h1 { font-size: 2rem; color: #1a1a1a; margin-bottom: 1rem; padding-bottom: 0.5rem; border-bottom: 2px solid #eee; }
        h2 { font-size: 1.5rem; color: #2c3e50; margin-top: 2rem; margin-bottom: 0.5rem; }
        h3 { font-size: 1.1rem; color: #555; margin-top: 1.5rem; margin-bottom: 0.5rem; }
        p { margin-bottom: 1rem; color: #444; }
        a { color: #3498db; }
        pre { background: #f8f9fa; border: 1px solid #e1e4e8; border-radius: 6px; padding: 16px; overflow-x: auto; margin: 1rem 0; }
        code { font-family: 'SF Mono', 'Monaco', 'Menlo', monospace; font-size: 0.9em; background: #f0f0f0; padding: 2px 6px; border-radius: 3px; }
        pre code { background: transparent; padding: 0; }
        hr { border: none; border-top: 1px solid #eee; margin: 2rem 0; }
        .file-path { color: #666; font-size: 0.9em; }
        .footer { margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #eee; color: #999; font-size: 0.85em; text-align: center; }
        @media print {
            body { padding: 1rem; }
            h1 { page-break-after: avoid; }
            h2 { page-break-before: always; }
            pre { page-break-inside: avoid; }
        }
    </style>
</head>
<body>
${selectedFiles
  .map((file, index) => {
    const title = file.header || file.filename;
    let html = '';

    if (index === 0) {
      html += `<h1>Repository Documentation</h1>\n`;
      html += `<p><em>Generated on ${new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      })}</em></p>\n`;
      html += `<hr>\n`;

      if (includeTOC) {
        html += `<h2>📑 Table of Contents</h2>\n<ol>\n`;
        selectedFiles.forEach((f, i) => {
          html += `<li><a href="#section-${i + 1}">${f.header || f.filename}</a></li>\n`;
        });
        html += `</ol>\n<hr>\n`;
      }
    }

    html += `<h2 id="section-${index + 1}">${index + 1}. ${escapeHtml(title)}</h2>\n`;

    if (showFilePaths && file.filepath) {
      html += `<p class="file-path"><strong>File:</strong> <code>${escapeHtml(file.filepath)}</code></p>\n`;
    }

    if (file.explanation) {
      html += `<h3>📝 Overview</h3>\n`;
      file.explanation
        .split('\n')
        .filter((p) => p.trim())
        .forEach((p) => {
          html += `<p>${escapeHtml(p.trim())}</p>\n`;
        });
    }

    if (file.code) {
      html += `<h3>💻 Source Code</h3>\n`;
      const lang = file.filetype || '';
      html += `<pre><code class="language-${escapeHtml(lang)}">${escapeHtml(file.code)}</code></pre>\n`;
    }

    if (file.footnote) {
      html += `<h3>📌 Notes</h3>\n`;
      html += `<p>${escapeHtml(file.footnote)}</p>\n`;
    }

    html += `<hr>\n`;
    return html;
  })
  .join('\n')}
<div class="footer">
    <p>Documentation generated by RepoDocs</p>
</div>
</body>
</html>`;
  }, [selectedFiles, includeTOC, showFilePaths]);

  function escapeHtml(text) {
    if (!text) return '';
    const map = { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' };
    return String(text).replace(/[&<>"']/g, (m) => map[m]);
  }

  // Export handlers
  const handleExportMarkdown = async () => {
    try {
      const result = await window.api.saveFile({
        content: generateMarkdown,
        defaultName: 'documentation.md',
        filters: [{ name: 'Markdown', extensions: ['md'] }],
      });
      if (result?.success) {
        alert(`Markdown saved to:\n${result.path}`);
      }
    } catch (error) {
      console.error('Export failed:', error);
      // Fallback: try clipboard
      handleCopyToClipboard(generateMarkdown, 'markdown');
    }
  };

  const handleExportHTML = async () => {
    try {
      const result = await window.api.saveFile({
        content: generateHTML,
        defaultName: 'documentation.html',
        filters: [{ name: 'HTML', extensions: ['html'] }],
      });
      if (result?.success) {
        alert(`HTML saved to:\n${result.path}`);
      }
    } catch (error) {
      console.error('Export failed:', error);
      // Fallback: try clipboard
      handleCopyToClipboard(generateHTML, 'html');
    }
  };

  const handleCopyToClipboard = async (content, type) => {
    try {
      await navigator.clipboard.writeText(content);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (error) {
      console.error('Copy failed:', error);
    }
  };

  const handleDownload = (content, filename, mimeType) => {
    const blob = new Blob([content], { type: mimeType });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className='h-full flex flex-col bg-white'>
      {/* Header */}
      <header className='flex items-center justify-between px-4 h-12 text-gray-200 bg-gray-800 border-b border-gray-200 flex-shrink-0'>
        <div className='flex items-center gap-4'>
          <button
            onClick={() => navigate('/')}
            className='flex items-center gap-1.5 px-2 py-1 text-sm text-gray-200 hover:text-gray-900 hover:bg-gray-100 rounded transition-colors'
          >
            <VscArrowLeft className='w-4 h-4' />
            Back
          </button>
          <h1 className='text-lg font-semibold text-gray-200'>Documentation Builder</h1>
        </div>

        <div className='flex items-center gap-2'>
          {/* Sidebar Toggle */}
          <button
            onClick={() => setShowSidebar(!showSidebar)}
            className={`p-2 rounded transition-colors ${
              showSidebar ? 'bg-blue-50 text-blue-600' : 'text-gray-500 hover:bg-gray-100'
            }`}
            title='Toggle sidebar'
          >
            <VscListTree className='w-4 h-4' />
          </button>

          {/* View Mode */}
          <div className='flex bg-gray-100 rounded-lg p-0.5'>
            <button
              onClick={() => setViewMode('preview')}
              className={`flex items-center gap-1 px-3 py-1 text-xs rounded transition-colors ${
                viewMode === 'preview' ? 'bg-white shadow text-gray-900' : 'text-gray-500'
              }`}
            >
              <VscEye className='w-3.5 h-3.5' />
              Preview
            </button>
            <button
              onClick={() => setViewMode('source')}
              className={`flex items-center gap-1 px-3 py-1 text-xs rounded transition-colors ${
                viewMode === 'source' ? 'bg-white shadow text-gray-900' : 'text-gray-500'
              }`}
            >
              <VscCode className='w-3.5 h-3.5' />
              Source
            </button>
            <button
              onClick={() => setViewMode('split')}
              className={`flex items-center gap-1 px-3 py-1 text-xs rounded transition-colors ${
                viewMode === 'split' ? 'bg-white shadow text-gray-900' : 'text-gray-500'
              }`}
            >
              <VscLayout className='w-3.5 h-3.5' />
              Split
            </button>
          </div>

          {/* Font Size */}
          <div className='flex items-center gap-1 bg-gray-100 rounded-lg p-0.5'>
            <button
              onClick={() => setFontSize((prev) => Math.max(10, prev - 2))}
              className='p-1 text-gray-500 hover:text-gray-700'
            >
              <VscZoomOut className='w-3.5 h-3.5' />
            </button>
            <span className='text-[10px] text-gray-500 w-8 text-center'>{fontSize}px</span>
            <button
              onClick={() => setFontSize((prev) => Math.min(20, prev + 2))}
              className='p-1 text-gray-500 hover:text-gray-700'
            >
              <VscZoomIn className='w-3.5 h-3.5' />
            </button>
          </div>

          {/* Settings */}
          <div className='flex items-center gap-1'>
            <button
              onClick={() => setShowLineNumbers(!showLineNumbers)}
              className={`p-1.5 rounded text-xs ${showLineNumbers ? 'bg-blue-50 text-blue-600' : 'text-gray-400 hover:bg-gray-100'}`}
              title='Line numbers'
            >
              <VscChecklist className='w-3.5 h-3.5' />
            </button>
            <button
              onClick={() => setShowFilePaths(!showFilePaths)}
              className={`p-1.5 rounded text-xs ${showFilePaths ? 'bg-blue-50 text-blue-600' : 'text-gray-400 hover:bg-gray-100'}`}
              title='File paths'
            >
              <VscFileCode className='w-3.5 h-3.5' />
            </button>
            <button
              onClick={() => setIncludeTOC(!includeTOC)}
              className={`p-1.5 rounded text-xs ${includeTOC ? 'bg-blue-50 text-blue-600' : 'text-gray-400 hover:bg-gray-100'}`}
              title='Table of contents'
            >
              <VscSettings className='w-3.5 h-3.5' />
            </button>
          </div>

          {/* Export Dropdown */}
          <div className='relative'>
            <button
              onClick={() => setShowExportMenu(!showExportMenu)}
              disabled={selectedFiles.length === 0}
              className='flex items-center gap-1.5 px-4 py-1.5 bg-blue-600 hover:bg-blue-700 disabled:opacity-50 
                                       disabled:cursor-not-allowed text-white text-sm rounded-lg transition-colors font-medium shadow-sm'
            >
              <VscSave className='w-4 h-4' />
              Export
            </button>

            {showExportMenu && (
              <>
                <div className='fixed inset-0 z-10' onClick={() => setShowExportMenu(false)} />
                <div className='absolute right-0 top-full mt-1 w-56 bg-white border border-gray-200 rounded-lg shadow-lg z-20'>
                  <div className='p-1.5'>
                    <button
                      onClick={() => {
                        handleDownload(generateMarkdown, 'documentation.md', 'text/markdown');
                        setShowExportMenu(false);
                      }}
                      className='w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded transition-colors'
                    >
                      <VscMarkdown className='w-4 h-4 text-blue-600' />
                      Export as Markdown (.md)
                    </button>
                    <button
                      onClick={() => {
                        handleDownload(generateHTML, 'documentation.html', 'text/html');
                        setShowExportMenu(false);
                      }}
                      className='w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded transition-colors'
                    >
                      <VscJson className='w-4 h-4 text-orange-600' />
                      Export as HTML (.html)
                    </button>
                    <hr className='my-1 border-gray-100' />
                    <button
                      onClick={() => {
                        handleCopyToClipboard(generateMarkdown, 'markdown');
                        setShowExportMenu(false);
                      }}
                      className='w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded transition-colors'
                    >
                      {copied ? (
                        <VscCheck className='w-4 h-4 text-green-600' />
                      ) : (
                        <VscCopy className='w-4 h-4 text-gray-500' />
                      )}
                      Copy Markdown
                    </button>
                    <button
                      onClick={() => {
                        handleCopyToClipboard(generateHTML, 'html');
                        setShowExportMenu(false);
                      }}
                      className='w-full flex items-center gap-2 px-3 py-2 text-sm text-gray-700 hover:bg-gray-100 rounded transition-colors'
                    >
                      {copied ? (
                        <VscCheck className='w-4 h-4 text-green-600' />
                      ) : (
                        <VscCopy className='w-4 h-4 text-gray-500' />
                      )}
                      Copy HTML
                    </button>
                  </div>
                </div>
              </>
            )}
          </div>
        </div>
      </header>

      <div className='flex-1 flex min-h-0'>
        {/* Sidebar */}
        {showSidebar && (
          <aside className='w-72 border-r border-gray-200 bg-gray-50 flex flex-col flex-shrink-0'>
            {/* Search */}
            <div className='p-3 border-b border-gray-200'>
              <div className='relative'>
                <VscSearch className='absolute left-2 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-gray-400' />
                <input
                  type='text'
                  placeholder='Search files...'
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className='w-full pl-7 pr-8 py-1.5 bg-white border border-gray-300 rounded text-sm 
                                               text-gray-700 placeholder-gray-400 focus:outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500'
                />
                {searchQuery && (
                  <button
                    onClick={() => setSearchQuery('')}
                    className='absolute right-2 top-1/2 -translate-y-1/2 text-gray-400 hover:text-gray-600'
                  >
                    <VscClose className='w-3 h-3' />
                  </button>
                )}
              </div>
            </div>

            {/* Header */}
            <div className='flex items-center justify-between p-3 border-b border-gray-200'>
              <h2 className='text-sm font-semibold text-gray-700'>Files</h2>
              <button
                onClick={handleSelectAll}
                className='text-xs text-blue-600 hover:text-blue-700 font-medium'
              >
                {allSelected ? 'Deselect All' : 'Select All'}
              </button>
            </div>

            {/* File List */}
            <div className='flex-1 overflow-y-auto p-2 space-y-1'>
              {filteredFiles.map((file) => {
                const isSelected = selectedIds.includes(file.id);
                const hasContent = !!contents[file.id];

                return (
                  <label
                    key={file.id}
                    className={`flex items-center gap-2 px-2 py-1.5 rounded cursor-pointer text-sm transition-colors
                                            ${
                                              isSelected
                                                ? 'bg-blue-50 text-blue-700 border border-blue-200'
                                                : 'text-gray-600 hover:bg-gray-100 border border-transparent'
                                            }`}
                  >
                    <input
                      type='checkbox'
                      checked={isSelected}
                      onChange={() => handleToggle(file.id)}
                      className='rounded border-gray-300 text-blue-600 focus:ring-blue-500 flex-shrink-0'
                    />
                    <VscFileCode
                      className={`w-3.5 h-3.5 flex-shrink-0 ${hasContent ? 'text-blue-500' : 'text-gray-400'}`}
                    />
                    <span className='truncate flex-1'>{file.filename}</span>
                    {file.header && (
                      <VscCircleFilled
                        className='w-2 h-2 text-green-500 flex-shrink-0'
                        title='Has documentation'
                      />
                    )}
                  </label>
                );
              })}
            </div>

            {/* Stats Footer */}
            <div className='p-3 border-t border-gray-200 bg-white'>
              <div className='flex items-center justify-between text-sm text-gray-500'>
                <span>{selectedIds.length} selected</span>
                <span>{files.length} total</span>
              </div>
            </div>
          </aside>
        )}

        {/* Document Content */}
        <div className='flex-1 overflow-auto bg-white' ref={printRef}>
          {viewMode === 'split' ? (
            <div className='grid grid-cols-2 h-full divide-x divide-gray-200'>
              {/* Source */}
              <div className='overflow-auto'>
                <pre
                  className='p-6 text-sm text-gray-700 font-mono whitespace-pre-wrap'
                  style={{ fontSize: `${fontSize}px` }}
                >
                  {exportFormat === 'markdown' ? generateMarkdown : generateHTML}
                </pre>
              </div>
              {/* Preview */}
              <div className='overflow-auto'>
                <div
                  className='p-6 prose prose-sm max-w-none'
                  style={{ fontSize: `${fontSize}px` }}
                >
                  {exportFormat === 'markdown' ? (
                    <pre className='whitespace-pre-wrap font-mono text-gray-300 bg-transparent'>
                      {generateMarkdown}
                    </pre>
                  ) : (
                    <div dangerouslySetInnerHTML={{ __html: generateHTML }} />
                  )}
                </div>
              </div>
            </div>
          ) : viewMode === 'source' ? (
            <pre
              className='p-6 text-sm text-gray-300 font-mono whitespace-pre-wrap'
              style={{ fontSize: `${fontSize}px` }}
            >
              {exportFormat === 'markdown' ? generateMarkdown : generateHTML}
            </pre>
          ) : (
            <div className='max-w-4xl mx-auto p-8' style={{ fontSize: `${fontSize}px` }}>
              {selectedFiles.length === 0 ? (
                <div className='flex items-center justify-center min-h-[400px]'>
                  <div className='text-center'>
                    <VscFileCode className='w-16 h-16 text-gray-300 mx-auto mb-4' />
                    <h2 className='text-xl font-semibold text-gray-700 mb-2'>No files selected</h2>
                    <p className='text-gray-500'>
                      Select files from the sidebar to build documentation
                    </p>
                  </div>
                </div>
              ) : exportFormat === 'markdown' ? (
                <div className='prose prose-sm max-w-none'>
                  <pre className='whitespace-pre-wrap font-mono text-gray-300 bg-gray-50 p-4 rounded-lg border'>
                    {generateMarkdown}
                  </pre>
                </div>
              ) : (
                <div
                  className='prose prose-sm max-w-none'
                  dangerouslySetInnerHTML={{ __html: generateHTML }}
                />
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  );
}
